master:
  password: ${THEMEKIT_PASSWORD}
  theme_id: "133264179443"
  store: gonzaserra-test.myshopify.com

fix-bugs:
  password: ${THEMEKIT_PASSWORD}
  theme_id: "133904531699"
  store: gonzaserra-test.myshopify.com